### ISSUE TITLE
Regression in resolution change detection

### ISSUE THREAD

**Issue by marcmicalizzi** [yamashi/CyberEngineTweaks#422]
In the build supporting 1.1.0 it seems that https://github.com/yamashi/CyberEngineTweaks/issues/193 is no longer fixed

**Comment by FransBouma** [comment]
Yep, same here. My camera tools' dynamic resolution scaling feature also breaks now. While that's of lesser importance, I can't change the resolution again in the game settings, screen gets rendered wrong. Doesn't appear to be related to a setting. Can't find back a commit that fixed it previously, so not sure what to look for to fix it. @yamashi you know what fixed it previously, or which commit?

**Comment by FransBouma** [comment]
The resize buffer call returns an error, see the Reshade Log below. (without reshade, same prob, so that's not the issue). No overlays running, no additional tools hooking into dx12. 

```
11:52:46:469 [06432] | INFO  | Redirecting CreateDXGIFactory1(riid = {7B7166EC-21C7-44AE-B21A-C9AE321AE369}, ppFactory = 000000BBE17FF1C8) ...
11:52:46:479 [06432] | INFO  | Redirecting IDXGISwapChain::SetFullscreenState(this = 00000266B04C6DF0, Fullscreen = FALSE, pTarget = 0000000000000000) ...
11:52:46:480 [06432] | INFO  | Redirecting IDXGISwapChain::ResizeBuffers(this = 00000266B04C6DF0, BufferCount = 3, Width = 1600, Height = 1024, NewFormat = 28, SwapChainFlags = 0x800) ...
11:52:46:482 [06432] | INFO  | Destroyed runtime environment on runtime 00000266A313B290.
11:52:46:485 [06432] | WARN  | IDXGISwapChain::ResizeBuffers failed with error code DXGI_ERROR_INVALID_CALL.
11:52:46:489 [06432] | INFO  | Recreated runtime environment on runtime 00000266A313B290.
```
The window does resize, the viewport's resolution does not. 

You don't release the D3D12 pointers you obtained from DX12, you just set the objects to a nullptr. This doesn't work (see: https://github.com/yamashi/CyberEngineTweaks/blob/master/src/d3d12/D3D12_Functions.cpp#L23), you have to call `Release()` on them. 
E.g. what I'm doing in CyberLit: (don't mind the CriticalSection, it was mainly a safeguard to make sure multi-threaded calls weren't causing crashes.)

```cpp
typedef HRESULT(WINAPI* tIDXGISwapChain_ResizeBuffers)(IDXGISwapChain*, UINT, UINT, UINT, DXGI_FORMAT, UINT);
tIDXGISwapChain_ResizeBuffers oSwapChain_ResizeBuffers = nullptr;
HRESULT WINAPI hSwapChain_ResizeBuffers(IDXGISwapChain* pSwapChain, UINT BufferCount, UINT Width, UINT Height, DXGI_FORMAT NewFormat, UINT SwapChainFlags)
{
    LOG("IDXGISwapChain::ResizeBuffers::Begin\n");

    EnterCriticalSection(&_resizeBuffersCriticalSection);
    s_resizing = true;
    if (g_initialized)
    {
        CloseHandle(g_fenceEvent);

        for (int i = 0; i < g_backBufferCount; ++i)
        {
        	FrameContext* frameCtxt = &g_frameContexts[i];
            frameCtxt->Fence->Release();
            frameCtxt->CommandAllocator->Release();
            frameCtxt->FenceValue = 0;
        }
        g_pd3dRtvDescHeap->Release();
        g_pd3dSrvDescHeap->Release();
        g_pd3dCommandList->Release();

    	ImGui_ImplDX12_Shutdown();
        g_initialized = false;
    }

    HRESULT toReturn = oSwapChain_ResizeBuffers(pSwapChain, BufferCount, Width, Height, NewFormat, SwapChainFlags);

    s_reinitializeWait = 10;
    s_reinitialize = true;

    s_resizing = false;
    LeaveCriticalSection(&_resizeBuffersCriticalSection);
    LOG("IDXGISwapChain::ResizeBuffers::End\n");
    return toReturn;
}
```

g_pd3dRtvDescHeap etc. are normal pointers:
```cpp
static ID3D12DescriptorHeap*                g_pd3dRtvDescHeap = nullptr;
static ID3D12DescriptorHeap*                g_pd3dSrvDescHeap = nullptr;
static ID3D12CommandQueue*                  g_pd3dCommandQueue = nullptr;
static ID3D12GraphicsCommandList*           g_pd3dCommandList = nullptr;
```

I think this is introduced when you removed the ComPtr wrappers, @WSSDude420 ? 
What surprises me a bit is that you don't use any fences.

**Comment by FransBouma** [comment]
For the life of me I can't get xmake to build a debug build. In vs I get 30+ errors, so that's a no go, on the command line xmake refuses to build a debug build so checking things is a big hard without a pdb. I changed some code to introduce the releases, not re-init the swapchain/device, wait a few frames between destroy and re-init, draw overlay only when not resizing, but there's still a bug somewhere as the behavior doesn't change: call still fails with INVALID CALL, reshade also reports the commandqueue has an invalid ref counting, but I don't see how that could be a problem as it's not removed.

**Comment by WSSDude420** [comment]
I didnt think we own any of those resources tbh, that is why I removed ComPtrs. Forgot about those though, yeah....

Problem with having all in ComPtrs before was they were causing crashes on exit, always, even when CrashReporter didnt pop up. 
Always was double-freed somehow, first by us and then by whatever else came next (game or reshade, both were crashing)

Without them, all seemed to work, although I forgot to test resizing game window...
So I assumed that ResizeBuffers is reliable enough for reseting these and said F to those ComPtrs, as we as a hook dont really need reference necessarily to it (at least that is what I thought).

Already know proper fix, am just lazy :P
Will for sure be fixed though, dont worry. Or if you want to help, can always PR i guess.

**Comment by WSSDude420** [comment]
xmake is kind of retarded tbh :P 

For me to make it work like I would expect it to work, I had to install it into PowerShell with Scoop...
After that, if I wanted to use solutions, I found out I also have to have standalone installed... So I basically have two xmakes now :D

Seems to work at least. Just having one or the other seems to break either PowerShell or Visual Studio...

Other thing is Visual Studio 2019 is required, you need to have latest version (prolly some older will work too, but there was some compiler bug which was fixed)

What may help it get on its knees is also executing these:
```
xmake repo -u
xmake f -c
```

This should update and recompile packages.

**Comment by FransBouma** [comment]
> Already know proper fix, am just lazy :P Will for sure be fixed though, dont worry. Or if you want to help, can always PR i guess.

If you know what to fix, just tell me and I'll implement it right now :) Yeah the comptrs aren't needed, you just get a pointer from the framework, which you have to release if you get rid of it. Setting things to nullptr doesn't do that :P

xmake apparently doesn't see any targets, it does build 'a' target, but if I specify `xmake -b debug`  (or release) it says it can't find the target, xmake.lua shows these targets are expected, but alas... no dice. In vs2019 I get a lot of 'std has no member 'vector'' kind of errors, which are bizarre (I'm on 16.8.3), likely a pch that's not done... anyway... if you can tell me what the error is I can implement it and send you a PR

**Comment by WSSDude420** [comment]
```xmake f -m debug
xmake -y```

doesnt build debug version?

and problem is exactly with those - we create those and do not release them. crashing on exit was most probably linked to us trying to use ComPtr on swapchain+command queue from what i quickly tested

technically, reverting my changes for everything except these two should be enough to fix it, but i didnt test it that thoroughly.

**Comment by WSSDude420** [comment]
One thing which came to my mind btw regarding compile issues, but that has prolly nothing to do with this rn...

ATL package is required, as we utilize ATL.

But that would prolly not build release too so i dont think this is an issue here now. Just something that popped to my mind which is not mentioned.

**Comment by FransBouma** [comment]
I did add the required Release() calls but it still shows the same issue, hence I wanted to debug the code. The problem I now have is that the xmake f -c command failed to pull TiltedCore ` => download https://github.com/tiltedphoques/TiltedCore/releases/download/v0.1.5/release.zip .. failed` and every subsequent xmake -f c simply skips that. xmake f -m debug + xmake -y dies in stdafx.h now
```
C:\Users\frans.SD\Documents\GitHub\CyberEngineTweaks>xmake -y
[  0%]: compiling.release src\stdafx.h
error: stdafx.h
C:\Users\frans.SD\AppData\Local\.xmake\packages\t\tiltedcore\v0.1.5\8574311f4b544fa89a3d8c3ee79d1929\include\TiltedCore\Stl.hpp(5): fatal error C1083: Cannot open include file: 'tsl/hopscotch_map.h': No such file or directory
```
I'll retry from scratch

**Comment by WSSDude420** [comment]
Try to reset xmake cache, could be borked.

This can be done by deleting .xmake folder.

**Comment by FransBouma** [comment]
Nope, it fails on the TiltedCore package, as it requires a release.zip being there, but on the tilted core repo the release only contains the default 2 source archives, not a release .zip. 

Ok, I'll give up for now.

**Comment by WSSDude420** [comment]
@FransBouma Building issues should be resolved with latest push.

Notified yamashi on Discord, as TiltedCore was his. All should work fine now.

**Comment by FransBouma** [comment]
Built from source, all works fine now, thanks @WSSDude420 and @yamashi :)
